name: Set Secrets

on:
  push:
    branches:
      - main

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set ORCID secrets
        run: |
          echo "ORCID_CLIENT_ID=${{ secrets.ORCID_CLIENT_ID }}"
          echo "ORCID_CLIENT_SECRET=${{ secrets.ORCID_CLIENT_SECRET }}"
